<?php

/**
 * @file
 * Module file to alter behaviour.
 */

/**
 * Implements hook_menu_local_tasks_alter().
 */
function as_user_options_menu_local_tasks_alter(&$data, $route_name) {
  // hides user tab
  $config_factory = \Drupal::service('config.factory');
  $hide_tabs = $config_factory->get('as_user_options.settings')->get('hideusertabs');

    if ($route_name == 'user.login'  && isset($data['tabs'][0])) {
        if ($hide_tabs) {
          // Remove all tabs from user login form.
          foreach ($data['tabs'][0] as $key => $tab) {
            $data['tabs'][0][$key]['#access'] = FALSE;
          }
        }
    }

}


/**
 * Implements hook_toolbar_alter().
 */

function as_user_options_toolbar_alter(&$items) {
    // hides shortcuts
    //$result = json_decode(json_encode($items['user']['tab']));
    //var_dump($result);
    $config_factory = \Drupal::service('config.factory');
    $hide_shortcuts = $config_factory->get('as_user_options.settings')->get('hideshortcuts');
    if ($hide_shortcuts) {
        $items['shortcuts']['#wrapper_attributes']['class'] = 'visually-hidden';
    }
    // rename a thing
    //$items['user']['tab']['#title'] = "Manage User";
}


/**
 * Implements hook_preprocess_HOOK().
 */
function as_user_options_preprocess_links__toolbar_user(&$variables) {
  // Remove the 'View profile' and 'Edit profile' menu items.
    //$result = json_decode(json_encode($variables));
    //var_dump($result);
    $config_factory = \Drupal::service('config.factory');
    $hide_view = $config_factory->get('as_user_options.settings')->get('hideviewprofile');
    $hide_edit = $config_factory->get('as_user_options.settings')->get('hideeditprofile');
    if ($hide_view) {
        unset($variables['links']['account']);
    }
    if ($hide_edit) {
        unset($variables['links']['account_edit']);
    }
}
