<?php

/**
 * @file
 * Module file to alter behaviour.
 */

/**
 * Implements hook_menu_local_tasks_alter().
 */
function as_user_options_menu_local_tasks_alter(&$data, $route_name) {
  $config_factory = \Drupal::service('config.factory');
  $hide_tabs = $config_factory->get('as_user_options.settings')->get('hideusertabs');

  // Hide user tabs on login form.
  if ($route_name == 'user.login' && isset($data['tabs'][0])) {
    if ($hide_tabs) {
      // Remove all tabs from user login form.
      foreach ($data['tabs'][0] as $key => $tab) {
        $data['tabs'][0][$key]['#access'] = FALSE;
      }
    }
  }
}


/**
 * Implements hook_toolbar_alter().
 */
function as_user_options_toolbar_alter(&$items) {
  // Get roles for current user.
  $current_user = \Drupal::currentUser();
  $roles = $current_user->getRoles();

  $config_factory = \Drupal::service('config.factory');
  $hide_shortcuts = $config_factory->get('as_user_options.settings')->get('hideshortcuts');
  $hide_manage = $config_factory->get('as_user_options.settings')->get('hidemanage');

  // Hide shortcuts.
  if ($hide_shortcuts) {
    $items['shortcuts']['#access'] = FALSE;
  }

  // Hide manage for users who are faculty, student, or staff who are not also editor or contributor.
  if ($hide_manage && (in_array('faculty', $roles) || in_array('student', $roles) || in_array('staff', $roles))) {
    if (!in_array('editor', $roles) && !in_array('contributor', $roles)) {
      $items['administration']['#access'] = FALSE;
    }
  }
}


/**
 * Implements hook_preprocess_HOOK().
 */
function as_user_options_preprocess_links__toolbar_user(&$variables) {
  $config_factory = \Drupal::service('config.factory');
  $hide_view = $config_factory->get('as_user_options.settings')->get('hideviewprofile');
  $hide_edit = $config_factory->get('as_user_options.settings')->get('hideeditprofile');

  // Remove 'View profile' menu item.
  if ($hide_view) {
    unset($variables['links']['account']);
  }

  // Remove 'Edit profile' and admin menu items.
  if ($hide_edit) {
    unset($variables['links']['account_edit']);
    unset($variables['links']['admin']);
  }
}
